### ISSUE TITLE
Issue with stencil loader

### ISSUE THREAD

**Issue by miriamgonp** [alexlafroscia/ember-cli-stencil#21]
Hi, 
I trying to import a simple `hello world` stencil project in my ember project.
I just installed `ember-cli-stencil` into an ember project (version 3.7.0).  and now it fails to build with the error:
```Build Error (Bundler)

Can't resolve 'ditto/loader' 
```
Any idea what is going on?

**Comment by miriamgonp** [comment]
I solved the problem adding `"prepare": "npm run build --prod",` In `package.json`

**Comment by alexlafroscia** [comment]
Just to clarify, you added that to the scripts of your Stencil project?
